---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true
  customize:
    memory: 384

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[play::default]
  - name: source
    run_list:
      - recipe[play::source]
